admin:
  admin.manage_users: true
  admin.create_client: true
  admin.edit_asset_config: true
  admin.modify_role_permission: true
  admin.view_action_logs: true
  admin.trigger_global_killswitch: true
  admin.intraday_trigger_control: true
  trader.submit_manual_trade: false
  trader.view_portfolio: false
  trader.view_approval_status: false
  risker.approve_trade: false
  risker.view_intraday_trigger_log: false
  risker.view_risk_insight: false
  risker.trigger_global_killswitch: false
  auditor.view_audit_decisions: false
  auditor.view_daily_summary: false
  auditor.trace_intent: false
  auditor.view_periodic_scan_logs: false
  auditor.view_risk_triggers: false
  compliance_officer.view_logs: false
  compliance_officer.view_overrides: false
  compliance_officer.edit_rules: false
  quant_researcher.run_strategy: false
  strategy_agent.run_passive_rebalance: false
  reporter.view_daily: false
  reporter.view_monthly: false
  reporter.view_attribution: false
trader:
  admin.manage_users: false
  admin.create_client: false
  admin.edit_asset_config: false
  admin.modify_role_permission: false
  admin.view_action_logs: false
  admin.trigger_global_killswitch: false
  admin.intraday_trigger_control: false
  trader.submit_manual_trade: true
  trader.view_portfolio: true
  trader.view_approval_status: true
  risker.approve_trade: false
  risker.view_intraday_trigger_log: false
  risker.view_risk_insight: false
  risker.trigger_global_killswitch: false
  auditor.view_audit_decisions: false
  auditor.view_daily_summary: false
  auditor.trace_intent: false
  auditor.view_periodic_scan_logs: false
  auditor.view_risk_triggers: false
  compliance_officer.view_logs: false
  compliance_officer.view_overrides: false
  compliance_officer.edit_rules: false
  quant_researcher.run_strategy: false
  strategy_agent.run_passive_rebalance: false
  reporter.view_daily: false
  reporter.view_monthly: false
  reporter.view_attribution: false
  trader.export_data: true
risker:
  admin.manage_users: false
  admin.create_client: false
  admin.edit_asset_config: false
  admin.modify_role_permission: false
  admin.view_action_logs: false
  admin.trigger_global_killswitch: false
  admin.intraday_trigger_control: false
  trader.submit_manual_trade: false
  trader.view_portfolio: false
  trader.view_approval_status: false
  risker.approve_trade: true
  risker.view_intraday_trigger_log: true
  risker.view_risk_insight: true
  risker.trigger_global_killswitch: true
  auditor.view_audit_decisions: false
  auditor.view_daily_summary: false
  auditor.trace_intent: false
  auditor.view_periodic_scan_logs: false
  auditor.view_risk_triggers: false
  compliance_officer.view_logs: false
  compliance_officer.view_overrides: false
  compliance_officer.edit_rules: false
  quant_researcher.run_strategy: false
  strategy_agent.run_passive_rebalance: false
  reporter.view_daily: false
  reporter.view_monthly: false
  reporter.view_attribution: false
auditor:
  admin.manage_users: false
  admin.create_client: false
  admin.edit_asset_config: false
  admin.modify_role_permission: false
  admin.view_action_logs: false
  admin.trigger_global_killswitch: false
  admin.intraday_trigger_control: false
  trader.submit_manual_trade: false
  trader.view_portfolio: false
  trader.view_approval_status: false
  risker.approve_trade: false
  risker.view_intraday_trigger_log: false
  risker.view_risk_insight: false
  risker.trigger_global_killswitch: false
  auditor.view_audit_decisions: true
  auditor.view_daily_summary: true
  auditor.trace_intent: true
  auditor.view_periodic_scan_logs: true
  auditor.view_risk_triggers: true
  compliance_officer.view_logs: false
  compliance_officer.view_overrides: false
  compliance_officer.edit_rules: false
  quant_researcher.run_strategy: false
  strategy_agent.run_passive_rebalance: false
  reporter.view_daily: false
  reporter.view_monthly: false
  reporter.view_attribution: false
compliance_officer:
  admin.manage_users: false
  admin.create_client: false
  admin.edit_asset_config: false
  admin.modify_role_permission: false
  admin.view_action_logs: false
  admin.trigger_global_killswitch: false
  admin.intraday_trigger_control: false
  trader.submit_manual_trade: false
  trader.view_portfolio: false
  trader.view_approval_status: false
  risker.approve_trade: false
  risker.view_intraday_trigger_log: false
  risker.view_risk_insight: false
  risker.trigger_global_killswitch: false
  auditor.view_audit_decisions: false
  auditor.view_daily_summary: false
  auditor.trace_intent: false
  auditor.view_periodic_scan_logs: false
  auditor.view_risk_triggers: false
  compliance_officer.view_logs: true
  compliance_officer.view_overrides: true
  compliance_officer.edit_rules: true
  quant_researcher.run_strategy: false
  strategy_agent.run_passive_rebalance: false
  reporter.view_daily: false
  reporter.view_monthly: false
  reporter.view_attribution: false
quant_researcher:
  admin.manage_users: false
  admin.create_client: false
  admin.edit_asset_config: false
  admin.modify_role_permission: false
  admin.view_action_logs: false
  admin.trigger_global_killswitch: false
  admin.intraday_trigger_control: false
  trader.submit_manual_trade: false
  trader.view_portfolio: false
  trader.view_approval_status: false
  risker.approve_trade: false
  risker.view_intraday_trigger_log: false
  risker.view_risk_insight: false
  risker.trigger_global_killswitch: false
  auditor.view_audit_decisions: false
  auditor.view_daily_summary: false
  auditor.trace_intent: false
  auditor.view_periodic_scan_logs: false
  auditor.view_risk_triggers: false
  compliance_officer.view_logs: false
  compliance_officer.view_overrides: false
  compliance_officer.edit_rules: false
  quant_researcher.run_strategy: true
  strategy_agent.run_passive_rebalance: false
  reporter.view_daily: false
  reporter.view_monthly: false
  reporter.view_attribution: false
strategy_agent:
  admin.manage_users: false
  admin.create_client: false
  admin.edit_asset_config: false
  admin.modify_role_permission: false
  admin.view_action_logs: false
  admin.trigger_global_killswitch: false
  admin.intraday_trigger_control: false
  trader.submit_manual_trade: false
  trader.view_portfolio: false
  trader.view_approval_status: false
  risker.approve_trade: false
  risker.view_intraday_trigger_log: false
  risker.view_risk_insight: false
  risker.trigger_global_killswitch: false
  auditor.view_audit_decisions: false
  auditor.view_daily_summary: false
  auditor.trace_intent: false
  auditor.view_periodic_scan_logs: false
  auditor.view_risk_triggers: false
  compliance_officer.view_logs: false
  compliance_officer.view_overrides: false
  compliance_officer.edit_rules: false
  quant_researcher.run_strategy: false
  strategy_agent.run_passive_rebalance: true
  reporter.view_daily: false
  reporter.view_monthly: false
  reporter.view_attribution: false
reporter:
  admin.manage_users: false
  admin.create_client: false
  admin.edit_asset_config: false
  admin.modify_role_permission: false
  admin.view_action_logs: false
  admin.trigger_global_killswitch: false
  admin.intraday_trigger_control: false
  trader.submit_manual_trade: false
  trader.view_portfolio: false
  trader.view_approval_status: false
  risker.approve_trade: false
  risker.view_intraday_trigger_log: false
  risker.view_risk_insight: false
  risker.trigger_global_killswitch: false
  auditor.view_audit_decisions: false
  auditor.view_daily_summary: false
  auditor.trace_intent: false
  auditor.view_periodic_scan_logs: false
  auditor.view_risk_triggers: false
  compliance_officer.view_logs: false
  compliance_officer.view_overrides: false
  compliance_officer.edit_rules: false
  quant_researcher.run_strategy: false
  strategy_agent.run_passive_rebalance: false
  reporter.view_daily: true
  reporter.view_monthly: true
  reporter.view_attribution: true
testengine:
  testengine.run_test: true
  testengine.view_debug_output: true
  testengine.simulate_risk_trigger: true
observer:
  observer.view_only_mode: true
  observer.inspect_config: true
  observer.trace_only: true

